<a href="https://colab.research.google.com/github/rai8896/Deep_Learning_Lab/blob/main/DL_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment-> 1

Create 1D, 2D, and 3D tensors using PyTorch and NumPy.
Show Basic Operations: Element-wise addition, subtraction, multiplication, and division.
Dot product and matrix multiplication.
Indexing and Slicing examples (Boolean masking, extracting subtensors)
Use .view(), .reshape(), .unsqueeze(), and .squeeze() in PyTorch. Compare with .reshape in Numpy
Broadcasting- Perform operations with tensors of different shapes.
In-place vs Out-of-place operations

1. Create 1D, 2D, and 3D tensors using PyTorch and NumPy.

In [ ]:
import torch
import numpy as np

t1 = torch.tensor([1, 2, 3]) # 1 dimensional tensor
print("1D Tensor:\n", t1)

t2 = torch.tensor([[1, 2], [3, 4]]) #2 dimension tensor
print("\n2D Tensor:\n", t2)

t3 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) #3 dimensional tensor
print("\n3D Tensor:\n", t3)


n1 = np.array([1, 2, 3])# 1D Array


n2 = np.array([[1, 2], [3, 4]]) # 2D Array


n3 = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])# 3D Array

print("\nNumPy 1D:\n", n1)
print("\nNumPy 2D:\n", n2)
print("\nNumPy 3D:\n", n3)


1D Tensor:
 tensor([1, 2, 3])

2D Tensor:
 tensor([[1, 2],
        [3, 4]])

3D Tensor:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

NumPy 1D:
 [1 2 3]

NumPy 2D:
 [[1 2]
 [3 4]]

NumPy 3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


2. Show Basic Operations: Element-wise addition, subtraction, multiplication, and division.

In [ ]:
a = torch.tensor([10, 20, 30])
b = torch.tensor([2, 4, 5])

print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: tensor([12, 24, 35])
Subtraction: tensor([ 8, 16, 25])
Multiplication: tensor([ 20,  80, 150])
Division: tensor([5., 5., 6.])


3.  Dot product and matrix multiplication.

In [ ]:
x_pt = torch.tensor([1, 2, 3])
y_pt = torch.tensor([4, 5, 6])
print("\nPyTorch Dot Product:", torch.dot(x_pt, y_pt))

m1_pt = torch.tensor([[1, 2], [3, 4]])
m2_pt = torch.tensor([[5, 6], [7, 8]])
print("PyTorch Matrix Multiplication:\n", torch.matmul(m1_pt, m2_pt))


PyTorch Dot Product: tensor(32)
PyTorch Matrix Multiplication:
 tensor([[19, 22],
        [43, 50]])


4. Indexing and Slicing examples (Boolean masking, extracting subtensors)

In [ ]:
t_pt = torch.tensor([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("\nPyTorch Element:", t_pt[1, 2])
print("PyTorch Rows:\n", t_pt[:2])
print("PyTorch Column:\n", t_pt[:, 1])

mask_pt = t_pt > 50
print("PyTorch Boolean Mask:\n", t_pt[mask_pt])

print("PyTorch Sub-tensor:\n", t_pt[0:2, 1:3])



PyTorch Element: tensor(60)
PyTorch Rows:
 tensor([[10, 20, 30],
        [40, 50, 60]])
PyTorch Column:
 tensor([20, 50, 80])
PyTorch Boolean Mask:
 tensor([60, 70, 80, 90])
PyTorch Sub-tensor:
 tensor([[20, 30],
        [50, 60]])


5. Use .view(), .reshape(), .unsqueeze(), and .squeeze() in PyTorch.

In [ ]:
p_pt = torch.arange(1, 7)

print("\nPyTorch view():\n", p_pt.view(2, 3))
print("PyTorch reshape():\n", p_pt.reshape(3, 2))
print("PyTorch unsqueeze():", p_pt.unsqueeze(0).shape) # it means one single row with six element:
col_tensor = p_pt.unsqueeze(0)
print(col_tensor)
print("PyTorch unsqueeze():", p_pt.unsqueeze(1).shape) # it means 6  row with single element:
col_tensor = p_pt.unsqueeze(1)
print(col_tensor)
print("PyTorch squeeze():", p_pt.unsqueeze(0).squeeze().shape)

p_np = np.arange(1, 7)
print("\nNumPy reshape():\n", p_np.reshape(2, 3))


PyTorch view():
 tensor([[1, 2, 3],
        [4, 5, 6]])
PyTorch reshape():
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
PyTorch unsqueeze(): torch.Size([1, 6])
tensor([[1, 2, 3, 4, 5, 6]])
PyTorch unsqueeze(): torch.Size([6, 1])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
PyTorch squeeze(): torch.Size([6])

NumPy reshape():
 [[1 2 3]
 [4 5 6]]


6. Compare with .reshape in Numpy Broadcasting- Perform operations with tensors of different shapes. In-place vs Out-of-place operations

In [ ]:
A_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
B_pt = torch.tensor([10, 20, 30])
print("\nPyTorch Broadcasting:\n", A_pt + B_pt)

A_np = np.array([[1, 2, 3], [4, 5, 6]])
B_np = np.array([10, 20, 30])
print("\nNumPy Broadcasting:\n", A_np + B_np)


x_pt = torch.tensor([1, 2, 3])
y_pt = x_pt + 5  # Out-of-place
print("\nPyTorch Out-of-place:", y_pt)
x_pt.add_(5)  # In-place
print("PyTorch In-place:", x_pt)

x_np = np.array([1, 2, 3])
y_np = x_np + 5  # Out-of-place
print("\nNumPy Out-of-place:", y_np)
x_np += 5  # In-place
print("NumPy In-place:", x_np)






PyTorch Broadcasting:
 tensor([[11, 22, 33],
        [14, 25, 36]])

NumPy Broadcasting:
 [[11 22 33]
 [14 25 36]]

PyTorch Out-of-place: tensor([6, 7, 8])
PyTorch In-place: tensor([6, 7, 8])

NumPy Out-of-place: [6 7 8]
NumPy In-place: [6 7 8]
